global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  # Scrape do próprio Prometheus
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  # Scrape do Pushgateway
  - job_name: 'pushgateway'
    scrape_interval: 5s
    static_configs:
      - targets: ['pushgateway:9091']
